"""Key custody: letting a native agent or human take ownership of its identity.

Vantage's default is a *sealed seed* — each agent's and human's Nostr seed is
generated by the instance, encrypted with a key derived from
VANTAGE_SEED_MASTER_KEY, and stored in the instance's own database. That makes
the platform able to sign on their behalf, which is what every buzz_* feature
depends on. It also fixes the trust boundary at the instance: whoever operates
it can decrypt any account's seed and sign as them.

For an instance you run yourself that is fine. For an account on someone
else's instance it means you are a tenant, not a sovereign.

This module is the way out. An account proves control of a keypair it
generated itself, and the instance:

  * records that pubkey as the account's identity,
  * marks the account `key_custody='self'`,
  * and **destroys the sealed seed**.

That last step is the whole guarantee. Keeping the seed "just in case" would
leave the instance able to sign, which is precisely the power being given up.

## Why the guard matters more than the migration

Eighteen-odd modules call `derive_buzz_keypair(agent_id)` directly. After a
migration the derived key is no longer the account's identity — signing with
it would mint a *phantom* identity under a pubkey the account does not
control, silently, and publish as if it were them.

So `get_or_create_sealed_seed` raises `SelfCustodyError` for a self-custody
account rather than returning a key. Every one of those call sites fails
loudly instead of quietly signing as the wrong identity. A feature that has
not been taught about self-custody breaks visibly, which is the correct
outcome for a security boundary.

## What the account gives up

Everything that needs Vantage to sign. It publishes to the relay itself, with
its own key, exactly as an external agent does. The trade is stated plainly at
the endpoint rather than buried here.
"""
import json
import logging
import secrets
import time
from typing import Optional

import aiosqlite

from .coordination_join import JoinRejected, check_proof
from .db import get_db

logger = logging.getLogger(__name__)

CHALLENGE_TTL_SECONDS = 600

# Custody states. 'derived' is the default and matches the sealed-seed
# behaviour every existing account has today.
CUSTODY_DERIVED = "derived"
CUSTODY_SELF = "self"


class SelfCustodyError(RuntimeError):
    """Raised when something asks Vantage to sign for an account that holds
    its own key.

    Not a failure to route around: the caller is about to sign as an identity
    the account does not control. The fix is for that feature to have the
    account sign for itself, not to fall back to a derived key.
    """


async def init_sovereignty_db() -> None:
    async with get_db() as db:
        for table, extra in (("agents", ""), ("humans", "")):
            for col, ddl in (
                ("key_custody", f"TEXT NOT NULL DEFAULT '{CUSTODY_DERIVED}'"),
                ("self_custody_pubkey", "TEXT DEFAULT NULL"),
                ("custody_migrated_at", "TEXT DEFAULT NULL"),
            ):
                try:
                    await db.execute(f"ALTER TABLE {table} ADD COLUMN {col} {ddl}{extra}")
                except Exception:
                    pass  # already present

        await db.execute("""
            CREATE TABLE IF NOT EXISTS custody_challenges (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                challenge TEXT NOT NULL UNIQUE,
                subject_kind TEXT NOT NULL,        -- agent | human
                subject_id INTEGER NOT NULL,
                pubkey TEXT NOT NULL,
                expires_at INTEGER NOT NULL,
                consumed_at TEXT,
                created_at TEXT DEFAULT (datetime('now'))
            )
        """)

        # An irreversible, security-relevant change deserves a record that
        # survives it. Keeps the prior pubkey so history published under the
        # old identity stays attributable.
        await db.execute("""
            CREATE TABLE IF NOT EXISTS custody_migrations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                subject_kind TEXT NOT NULL,
                subject_id INTEGER NOT NULL,
                prior_pubkey TEXT,
                new_pubkey TEXT NOT NULL,
                principal_id INTEGER,
                migrated_at TEXT DEFAULT (datetime('now'))
            )
        """)
        await db.execute(
            "CREATE INDEX IF NOT EXISTS idx_custody_migrations_subject "
            "ON custody_migrations(subject_kind, subject_id)"
        )
        await db.commit()


# ── custody lookup ───────────────────────────────────────────────────────────

async def agent_custody(agent_id: int) -> str:
    return await _custody("agents", agent_id)


async def human_custody(human_id: int) -> str:
    return await _custody("humans", human_id)


async def _custody(table: str, subject_id: int) -> str:
    async with get_db() as db:
        try:
            cur = await db.execute(
                f"SELECT key_custody FROM {table} WHERE id=?", (subject_id,)
            )
            row = await cur.fetchone()
        except Exception:
            # Column not created yet (init hasn't run). Everything is derived.
            return CUSTODY_DERIVED
    return (row[0] if row and row[0] else CUSTODY_DERIVED)


async def custody_status(*, agent_id: Optional[int] = None, human_id: Optional[int] = None) -> dict:
    table, subject_id = ("agents", agent_id) if agent_id is not None else ("humans", human_id)
    async with get_db() as db:
        db.row_factory = aiosqlite.Row
        try:
            cur = await db.execute(
                f"SELECT key_custody, self_custody_pubkey, custody_migrated_at "
                f"FROM {table} WHERE id=?",
                (subject_id,),
            )
            row = await cur.fetchone()
        except Exception:
            row = None
    row = dict(row) if row else {}
    custody = row.get("key_custody") or CUSTODY_DERIVED
    return {
        "key_custody": custody,
        "pubkey": row.get("self_custody_pubkey"),
        "migrated_at": row.get("custody_migrated_at"),
        "sovereign": custody == CUSTODY_SELF,
        "explanation": (
            "You hold this identity's private key. This instance cannot sign as you, "
            "and cannot recover the identity if you lose the key."
            if custody == CUSTODY_SELF else
            "This instance holds a sealed seed for this identity and can sign on its "
            "behalf. Migrate to self-custody to end that."
        ),
    }


# ── the migration ────────────────────────────────────────────────────────────

async def issue_custody_challenge(*, subject_kind: str, subject_id: int, pubkey: str) -> dict:
    if subject_kind not in ("agent", "human"):
        raise JoinRejected("subject_kind must be 'agent' or 'human'")
    pubkey = (pubkey or "").strip().lower()
    if len(pubkey) != 64:
        raise JoinRejected("pubkey must be 64 hex characters (x-only, as Nostr uses)")
    try:
        bytes.fromhex(pubkey)
    except ValueError as exc:
        raise JoinRejected("pubkey is not valid hex") from exc

    # A pubkey already in use is refused: two principals sharing an identity
    # would make the whole log ambiguous about who said what.
    existing = await _principal_by_pubkey(pubkey)
    if existing:
        raise JoinRejected("that pubkey already belongs to a principal on this instance")

    challenge = secrets.token_hex(32)
    async with get_db() as db:
        await db.execute(
            """INSERT INTO custody_challenges
                 (challenge, subject_kind, subject_id, pubkey, expires_at)
               VALUES (?,?,?,?,?)""",
            (challenge, subject_kind, subject_id, pubkey,
             int(time.time()) + CHALLENGE_TTL_SECONDS),
        )
        await db.commit()

    return {
        "challenge": challenge,
        "expires_at": int(time.time()) + CHALLENGE_TTL_SECONDS,
        "kind": 22242,
        "warning": (
            "Confirming is irreversible. This instance will destroy its sealed seed for "
            "this identity and will no longer be able to sign for you — including for "
            "features that currently sign on your behalf. If you lose your key, the "
            "identity is gone."
        ),
    }


async def _consume_custody_challenge(challenge: str) -> dict:
    async with get_db() as db:
        db.row_factory = aiosqlite.Row
        cur = await db.execute("SELECT * FROM custody_challenges WHERE challenge=?", (challenge,))
        row = await cur.fetchone()
    if not row:
        raise JoinRejected("unknown challenge — request a new one")
    row = dict(row)
    if row["consumed_at"]:
        raise JoinRejected("this challenge has already been used")
    if int(row["expires_at"]) < int(time.time()):
        raise JoinRejected("challenge expired — request a new one")

    async with get_db() as db:
        cur = await db.execute(
            "UPDATE custody_challenges SET consumed_at=datetime('now') "
            "WHERE challenge=? AND consumed_at IS NULL",
            (challenge,),
        )
        await db.commit()
        if cur.rowcount != 1:
            raise JoinRejected("this challenge has already been used")
    return row


async def _principal_by_pubkey(pubkey: str) -> Optional[dict]:
    async with get_db() as db:
        db.row_factory = aiosqlite.Row
        try:
            cur = await db.execute("SELECT * FROM principals WHERE pubkey=?", (pubkey,))
            row = await cur.fetchone()
        except Exception:
            return None
    return dict(row) if row else None


async def migrate_to_self_custody(
    *, subject_kind: str, subject_id: int, signed_event: dict, challenge: str
) -> dict:
    """Take an account from sealed-seed custody to self-custody.

    Order matters. The proof is verified first, the identity is switched
    second, and the seed is destroyed last — so a failure at any point leaves
    the account able to keep working under its old identity rather than
    stranded with neither key.
    """
    pending = await _consume_custody_challenge(challenge)
    if pending["subject_kind"] != subject_kind or pending["subject_id"] != subject_id:
        raise JoinRejected("this challenge was issued for a different account")

    # Same verification as the external-agent join: recomputes the event id,
    # checks kind, pubkey match, challenge match and clock drift.
    check_proof(signed_event, pending["pubkey"], challenge)

    table = "agents" if subject_kind == "agent" else "humans"
    seed_column = "sealed_seed_enc" if subject_kind == "agent" else "buzz_sealed_seed_enc"
    new_pubkey = pending["pubkey"]

    prior_pubkey = None
    principal_id = None
    from . import coordination as coord

    try:
        if subject_kind == "agent":
            principal = await coord.get_or_create_agent_principal(subject_id)
        else:
            principal = await coord.get_or_create_human_principal(subject_id)
        prior_pubkey = principal["pubkey"]
        principal_id = principal["id"]
    except Exception as exc:
        # No principal yet (the account has never touched a guild). The
        # migration is still valid — one gets created on first use, with the
        # new pubkey.
        logger.info("custody: no existing principal for %s %s (%s)", subject_kind, subject_id, exc)

    async with get_db() as db:
        # Identity first.
        await db.execute(
            f"""UPDATE {table}
                   SET key_custody=?, self_custody_pubkey=?, custody_migrated_at=datetime('now')
                 WHERE id=?""",
            (CUSTODY_SELF, new_pubkey, subject_id),
        )
        if principal_id is not None:
            await db.execute(
                "UPDATE principals SET pubkey=?, key_custody=? WHERE id=?",
                (new_pubkey, CUSTODY_SELF, principal_id),
            )
        # Then the seed. This is the irreversible step and the actual
        # guarantee -- NULL, not a tombstone, so nothing can decrypt it.
        await db.execute(f"UPDATE {table} SET {seed_column}=NULL WHERE id=?", (subject_id,))
        if subject_kind == "agent":
            # The cached public half would otherwise still advertise the old
            # identity to every buzz_* reader.
            try:
                await db.execute(
                    "UPDATE agents SET nostr_pubkey_hex=?, sealed_seed_hex=NULL WHERE id=?",
                    (new_pubkey, subject_id),
                )
            except Exception as exc:
                logger.debug("silenced nostr_pubkey_hex update: %s", exc)

        await db.execute(
            """INSERT INTO custody_migrations
                 (subject_kind, subject_id, prior_pubkey, new_pubkey, principal_id)
               VALUES (?,?,?,?,?)""",
            (subject_kind, subject_id, prior_pubkey, new_pubkey, principal_id),
        )
        await db.commit()

    logger.info("custody: %s %s migrated to self-custody (%s -> %s)",
                subject_kind, subject_id, (prior_pubkey or "none")[:8], new_pubkey[:8])

    return {
        "key_custody": CUSTODY_SELF,
        "pubkey": new_pubkey,
        "prior_pubkey": prior_pubkey,
        "principal_id": principal_id,
        "sealed_seed_destroyed": True,
        "next": (
            "This instance can no longer sign for you. Publish to the relay yourself, "
            "authenticating with NIP-42 using your own key. Features that sign on an "
            "account's behalf will now refuse rather than sign as a different identity."
        ),
    }


async def relay_registration_pubkey(subject_kind: str, subject_id: int) -> Optional[str]:
    """The pubkey that should be registered on the relay for this account.

    Self-custody accounts still need relay membership to publish — they just
    supply the key rather than having it derived.
    """
    table = "agents" if subject_kind == "agent" else "humans"
    async with get_db() as db:
        try:
            cur = await db.execute(
                f"SELECT key_custody, self_custody_pubkey FROM {table} WHERE id=?", (subject_id,)
            )
            row = await cur.fetchone()
        except Exception:
            return None
    if row and row[0] == CUSTODY_SELF:
        return row[1]
    return None
