"""Runtime receipts, checked against a receipt the real kernel produced.

The vector in KERNEL_RECEIPT was generated by compiling
`Receipt::calculate_id` and `new_merkle` from omokoda-core verbatim against
the same blake3 and ed25519-dalek crates the kernel uses, and running them.
It is here so that a change to this verifier that "looks right" but hashes
the timestamp as bytes instead of as its decimal string -- or verifies the
signature against the decoded hash instead of the hex string -- fails
immediately rather than rejecting every real receipt in production.
"""
import copy
import secrets

import aiosqlite
import pytest
import pytest_asyncio

from backend import coordination as coord
from backend import receipts
from backend import work_refs as wr
from backend.db import get_db

# Produced by the kernel's own code paths. Do not regenerate by hand.
KERNEL_RECEIPT = {
    "agent_id": "agent-7",
    "action": "run_tests",
    "payload": "6a25564eebe3ccdfa2ed03fa8fa84de75532ddd8da03b347d6c1b2f5c8904255",
    "receipt_id": "44cb19ec7bf6a49d53821715185f781f8d99ff6cffbd7d93a07d186face23822",
    "previous_hash": "",
    "merkle_root": "abc123",
    "signature": (
        "45052ddccce6c77eb702a74278c9c101a7fa1c6793075737db55ff6a73f30ff7"
        "2f9dd97d07641bdc5a7520b6c67c397c6ef7a09d38e08a1e5759df111557260c"
    ),
    "timestamp": 1756000000,
    "nonce": 11400714819323198485,
}
KERNEL_PUBKEY = "197f6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d61"


@pytest_asyncio.fixture(scope="module", autouse=True)
async def schema(client):
    await coord.init_coordination_db()
    await wr.init_work_ref_db()
    await receipts.init_receipts_db()


@pytest_asyncio.fixture
async def principal_maker(fresh_agent):
    async def _make():
        agent = await fresh_agent()
        async with get_db() as db:
            db.row_factory = aiosqlite.Row
            cur = await db.execute("SELECT id FROM agents WHERE name=?", (agent["name"],))
            agent_id = dict(await cur.fetchone())["id"]
        return await coord.get_or_create_agent_principal(agent_id)
    return _make


@pytest_asyncio.fixture
async def signer():
    """A key we hold, for building chains longer than one receipt."""
    from nacl.signing import SigningKey

    key = SigningKey(bytes.fromhex("2b" * 32))

    def make(previous_hash="", action="act", nonce=None, timestamp=1756000001,
             agent_id="kernel-agent"):
        # A real nonce is a full random u64. Defaulting to one here keeps two
        # tests from colliding on the same receipt id, and exercises the
        # range that does not fit a signed 64-bit column.
        if nonce is None:
            nonce = secrets.randbits(64)
        body = {
            "agent_id": agent_id, "action": action,
            "payload": receipts._blake3_hex(action.encode(), b"{}"),
            "previous_hash": previous_hash, "merkle_root": "root",
            "timestamp": timestamp, "nonce": nonce,
        }
        body["receipt_id"] = receipts.compute_receipt_id(body)
        body["signature"] = key.sign(body["receipt_id"].encode()).signature.hex()
        return body

    make.pubkey = bytes(key.verify_key).hex()
    return make


# ── the hash, against the real kernel ────────────────────────────────────────

def test_the_receipt_id_matches_the_one_the_kernel_computed():
    assert receipts.compute_receipt_id(KERNEL_RECEIPT) == KERNEL_RECEIPT["receipt_id"]


def test_the_kernel_signature_verifies():
    receipts.verify_signature(
        KERNEL_RECEIPT["receipt_id"], KERNEL_RECEIPT["signature"], KERNEL_PUBKEY
    )


def test_the_signature_is_over_the_hex_string_not_the_decoded_hash():
    """The kernel signs `receipt_id.as_bytes()`. Verifying against the
    decoded 32 bytes is the plausible mistake, and it would reject every
    real receipt while looking entirely reasonable."""
    from nacl.signing import VerifyKey

    key = VerifyKey(bytes.fromhex(KERNEL_PUBKEY))
    signature = bytes.fromhex(KERNEL_RECEIPT["signature"])
    key.verify(KERNEL_RECEIPT["receipt_id"].encode(), signature)  # the real one
    with pytest.raises(Exception):
        key.verify(bytes.fromhex(KERNEL_RECEIPT["receipt_id"]), signature)


def test_the_integers_are_hashed_as_decimal_strings():
    """Hashing them as raw bytes produces a different id. This pins which."""
    variant = dict(KERNEL_RECEIPT, timestamp=KERNEL_RECEIPT["timestamp"] + 1)
    assert receipts.compute_receipt_id(variant) != KERNEL_RECEIPT["receipt_id"]


def test_a_receipt_missing_a_field_is_named_not_guessed():
    partial = {k: v for k, v in KERNEL_RECEIPT.items() if k != "merkle_root"}
    with pytest.raises(receipts.ReceiptError) as excinfo:
        receipts.compute_receipt_id(partial)
    assert "merkle_root" in str(excinfo.value)


def test_a_tampered_field_changes_the_id():
    tampered = dict(KERNEL_RECEIPT, action="rm -rf")
    assert receipts.compute_receipt_id(tampered) != KERNEL_RECEIPT["receipt_id"]


# ── key custody ──────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_a_receipt_without_a_registered_key_is_refused(client, principal_maker):
    p = await principal_maker()
    with pytest.raises(receipts.ReceiptError) as excinfo:
        await receipts.submit(principal=p, receipt=copy.deepcopy(KERNEL_RECEIPT))
    assert "no receipt key" in str(excinfo.value)


@pytest.mark.asyncio
async def test_a_malformed_key_is_refused_at_registration(client, principal_maker):
    p = await principal_maker()
    for bad in ["", "zz" * 32, "ab" * 10]:
        with pytest.raises(receipts.ReceiptError):
            await receipts.register_key(p["id"], bad)


@pytest.mark.asyncio
async def test_revoking_a_key_stops_new_receipts_but_keeps_old_ones(
    client, principal_maker, signer
):
    """Revocation is not a time machine."""
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    first = signer()
    await receipts.submit(principal=p, receipt=first)

    await receipts.revoke_key(p["id"], signer.pubkey)
    with pytest.raises(receipts.ReceiptError):
        await receipts.submit(principal=p, receipt=signer(previous_hash=first["receipt_id"]))
    assert await receipts.chain_head(p["id"]) == first["receipt_id"]


@pytest.mark.asyncio
async def test_a_second_key_can_be_registered_without_replacing_the_first(
    client, principal_maker, signer
):
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    await receipts.register_key(p["id"], KERNEL_PUBKEY, label="kernel")
    assert set(await receipts.active_keys(p["id"])) == {signer.pubkey, KERNEL_PUBKEY}


# ── verification ─────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_a_valid_receipt_is_accepted(client, principal_maker):
    p = await principal_maker()
    await receipts.register_key(p["id"], KERNEL_PUBKEY)
    result = await receipts.submit(principal=p, receipt=copy.deepcopy(KERNEL_RECEIPT))
    assert result["accepted"] is True
    assert result["receipt_id"] == KERNEL_RECEIPT["receipt_id"]


@pytest.mark.asyncio
async def test_a_receipt_whose_id_does_not_derive_from_its_fields_is_refused(
    client, principal_maker
):
    """Without this the signature would prove only that somebody signed *an*
    id, not that the id describes this action."""
    p = await principal_maker()
    await receipts.register_key(p["id"], KERNEL_PUBKEY)
    forged = dict(KERNEL_RECEIPT, action="deploy to production")
    with pytest.raises(receipts.ReceiptError) as excinfo:
        await receipts.submit(principal=p, receipt=forged)
    assert "does not derive" in str(excinfo.value)


@pytest.mark.asyncio
async def test_a_receipt_signed_by_the_wrong_key_is_refused(client, principal_maker, signer):
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    with pytest.raises(receipts.ReceiptError):
        await receipts.submit(principal=p, receipt=copy.deepcopy(KERNEL_RECEIPT))


@pytest.mark.asyncio
async def test_the_same_receipt_cannot_be_submitted_twice(client, principal_maker, signer):
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    receipt = signer()
    await receipts.submit(principal=p, receipt=receipt)
    with pytest.raises(receipts.ReceiptError) as excinfo:
        await receipts.submit(principal=p, receipt=receipt)
    assert "already been submitted" in str(excinfo.value)


# ── the chain ────────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_receipts_extend_the_chain(client, principal_maker, signer):
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    a = signer()
    await receipts.submit(principal=p, receipt=a)
    b = signer(previous_hash=a["receipt_id"])
    result = await receipts.submit(principal=p, receipt=b)
    assert result["chain_position"] == "extends"
    assert await receipts.chain_head(p["id"]) == b["receipt_id"]


@pytest.mark.asyncio
async def test_a_receipt_that_forks_the_chain_is_refused(client, principal_maker, signer):
    """Two receipts naming the same predecessor means one is not part of this
    history. Accepting both would make the chain decorative."""
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    a = signer()
    await receipts.submit(principal=p, receipt=a)
    await receipts.submit(principal=p, receipt=signer(previous_hash=a["receipt_id"]))

    fork = signer(previous_hash=a["receipt_id"])
    with pytest.raises(receipts.ReceiptError) as excinfo:
        await receipts.submit(principal=p, receipt=fork)
    assert "does not extend" in str(excinfo.value)


@pytest.mark.asyncio
async def test_two_principals_keep_separate_chains(client, principal_maker, signer):
    one, two = await principal_maker(), await principal_maker()
    for p in (one, two):
        await receipts.register_key(p["id"], signer.pubkey)
    a = signer(agent_id="one")
    await receipts.submit(principal=one, receipt=a)
    b = signer(agent_id="two")
    result = await receipts.submit(principal=two, receipt=b)
    assert result["chain_position"] == "start"


# ── binding to work ──────────────────────────────────────────────────────────

@pytest_asyncio.fixture
async def open_tro(principal_maker):
    poster = await principal_maker()
    async with get_db() as db:
        cur = await db.execute(
            """INSERT INTO tro_requests (agent_id, agent_name, service_type, description, status)
               VALUES (?,?,?,?,'open')""",
            (poster["agent_id"], poster["display_name"], "build", "Ship the thing"),
        )
        await db.commit()
        return cur.lastrowid


@pytest.mark.asyncio
async def test_a_receipt_binds_to_work_this_principal_claimed(
    client, principal_maker, signer, open_tro
):
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    ref = f"tro:{open_tro}"
    await wr.record_link(event_id=secrets.token_hex(32), channel_id=None, principal=p,
                         link_type=wr.LINK_CLAIM, raw_work_ref=ref)
    result = await receipts.submit(principal=p, receipt=signer(), work_ref=ref)
    assert result["work_ref"] == ref


@pytest.mark.asyncio
async def test_a_receipt_cannot_be_attached_to_someone_elses_claim(
    client, principal_maker, signer, open_tro
):
    """A valid receipt for one's own unrelated action must not become credit
    for another principal's delivery."""
    worker, outsider = await principal_maker(), await principal_maker()
    await receipts.register_key(outsider["id"], signer.pubkey)
    ref = f"tro:{open_tro}"
    await wr.record_link(event_id=secrets.token_hex(32), channel_id=None, principal=worker,
                         link_type=wr.LINK_CLAIM, raw_work_ref=ref)
    with pytest.raises(receipts.ReceiptError) as excinfo:
        await receipts.submit(principal=outsider, receipt=signer(), work_ref=ref)
    assert "claimed by another" in str(excinfo.value)


@pytest.mark.asyncio
async def test_a_receipt_naming_work_that_does_not_exist_is_refused(
    client, principal_maker, signer
):
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    with pytest.raises(receipts.ReceiptError) as excinfo:
        await receipts.submit(principal=p, receipt=signer(), work_ref="tro:99999999")
    assert "does not resolve" in str(excinfo.value)


# ── the wire ─────────────────────────────────────────────────────────────────

def test_an_accepted_receipt_does_not_mint_a_new_event_kind():
    """1902 is the ecosystem's attestation schema, and it is explicitly
    attestor-agnostic -- a runtime confirming its own execution is an
    attestor like any other."""
    from backend import nostr_kinds

    assert receipts.KIND_ATTESTATION == nostr_kinds.kind("attestation")
    assert not nostr_kinds.is_ours(receipts.KIND_ATTESTATION)


@pytest.mark.asyncio
async def test_a_full_range_u64_nonce_survives_storage(client, principal_maker, signer):
    """The kernel draws its nonce from the whole u64 range, and SQLite's
    INTEGER is signed 64-bit -- so an INTEGER column rejects roughly half of
    all real receipts. This is the case that found that."""
    p = await principal_maker()
    await receipts.register_key(p["id"], signer.pubkey)
    receipt = signer(nonce=2**64 - 1)
    result = await receipts.submit(principal=p, receipt=receipt)
    assert result["accepted"] is True

    chain = await receipts.chain_for_principal(p["id"])
    assert chain[0]["receipt_id"] == receipt["receipt_id"]
